# Generated by Django 4.2 on 2025-11-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_trainer_delete_entrenador_pokemon_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(default='', upload_to='pokemon_imagenes'),
            preserve_default=False,
        ),
    ]
